spring.profiles.active=postgres
# Hibernate Configuration
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:update}
spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}
# Server Configuration
server.port=${SERVER_PORT:5001}
# Swagger UI Configuration
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED:true}
springdoc.swagger-ui.path=${SWAGGER_UI_PATH:/swagger}
springdoc.swagger-ui.tags-sorter=${SWAGGER_UI_TAGS_SORTER:alpha}
springdoc.swagger-ui.operations-sorter=${SWAGGER_UI_OPERATIONS_SORTER:alpha}
# JWT Configuration
jwt.expiration=${JWT_EXPIRATION:1000000}
jwt.secret=${JWT_SECRET:softwaremethodologies123456789}
# openapi
backend.open-api.enabled=true
backend.open-api.api-version=1.0.0
backend.open-api.title=IoT
backend.open-api.description=Backend application integrating with firebase authentication and storage serv